---
- name: Ensure documentroot is present
  file:
    path: "{{ apache_docroot }}"
    owner: druadmin
    group: druadmin
    mode: 0755
    state: directory

- name: Create vhosts.d directory
  file:
    path: "{{ apache_root }}/vhosts.d"
    owner: root
    group: root
    mode: 0755
    state: directory

- name: Add configuration to include vhost configurations
  copy:
    src: includevhosts.conf
    dest: "{{ apache_root }}/conf.d/includevhostsd.conf"
    owner: root
    group: root
    mode: 0644
  notify: restart apache

- name: Upload http vhost
  template:
    src: http-vhost.conf.j2
    dest: "{{ apache_root }}/vhosts.d/{{ siteurl }}-http.conf"
    owner: root
    group: root
    mode: 0644
  vars:
    apache_listen_port: "80"
    documentroot: "{{ apache_docroot }}"
    servername: "{{ siteurl }}"
    accesslog: "{{ apache_root }}/logs/{{ siteurl }}-http-access.log"
    errorlog: "{{ apache_root }}/logs/{{ siteurl }}-http-error.log"
  notify: restart apache