---
- include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_distribution }}.yml"

- include_vars: 
    file: "../vars/samplesec.yml"

- include: install.yml
  tags: [installsclpackages]

- include: drush.yml
  tags: [config_drush]

- include: composer.yml
  tags: [config_composer]

- include: apache.yml
  tags: [config_apache]

- include: ssl.yml
  when: ssl
  tags: [config_ssl]