---
- name: Create Custom SSL PEM Directory
  file:
    path: "{{ apache_sslpemdir }}"
    owner: root
    group: root
    mode: 0755
    state: directory

- name: Create SSL Key
  copy:
    content: "{{ secret_files[siteurl].key }}"
    dest: "{{ apache_sslpemdir }}/{{ siteurl }}-key"
    owner: root
    group: root
    mode: 0600
  no_log: True

- name: Create SSL Certificate
  copy:
    content: "{{ secret_files[siteurl].crt }}"
    dest: "{{ apache_sslpemdir }}/{{ siteurl }}-crt"
    owner: root
    group: root
    mode: 0644
  no_log: True

- name: Create SSL Intermediate
  copy:
    content: "{{ secret_files[siteurl].interm }}"
    dest: "{{ apache_sslpemdir }}/{{ siteurl }}-interm"
    owner: root
    group: root
    mode: 0644
  no_log: True
  when: ssl and siteurl != 'localdev.local'

- name: Upload https vhost with self signed
  template:
    src: https-vhost.conf.j2
    dest: "{{ apache_root }}/vhosts.d/{{ siteurl }}-https.conf"
    owner: root
    group: root
    mode: 0644
  vars:
    apache_listen_port: "443"
    documentroot: "{{ apache_docroot }}"
    servername: "{{ siteurl }}"
    accesslog: "{{ apache_root }}/logs/{{ siteurl }}-http-access.log"
    errorlog: "{{ apache_root }}/logs/{{ siteurl }}-http-error.log"
    ssl_certificate_file: "{{ apache_sslpemdir }}/{{ siteurl }}-crt"
    ssl_certificate_key_file: "{{ apache_sslpemdir }}/{{ siteurl }}-key"
  notify: restart apache
  when: ssl and siteurl == 'localdev.local'

- name: Upload https vhost with intermediate
  template:
    src: https-vhost.conf.j2
    dest: "{{ apache_root }}/vhosts.d/{{ siteurl }}-https.conf"
    owner: root
    group: root
    mode: 0644
  vars:
    apache_listen_port: "443"
    documentroot: "{{ apache_docroot }}"
    servername: "{{ siteurl }}"
    accesslog: "{{ apache_root }}/logs/{{ siteurl }}-http-access.log"
    errorlog: "{{ apache_root }}/logs/{{ siteurl }}-http-error.log"
    ssl_certificate_file: "{{ apache_sslpemdir }}/{{ siteurl }}-crt"
    ssl_certificate_key_file: "{{ apache_sslpemdir }}/{{ siteurl }}-key"
    ssl_certificate_chain_file: "{{ apache_sslpemdir }}/{{ siteurl }}-interm"
  notify: restart apache
  when: ssl and siteurl != 'localdev.local'